document.addEventListener('DOMContentLoaded', function () {
  var canvas = document.querySelector('#snake-canvas');
  if (canvas) {
    var ctx = canvas.getContext('2d'), size = 20, cols = 24, rows = 14;
    var snake, direction, nextDirection, food, score, loop;
    function randomFood(){ var p; do { p={x:Math.floor(Math.random()*cols),y:Math.floor(Math.random()*rows)}; } while(snake.some(function(s){return s.x===p.x&&s.y===p.y;})); return p; }
    function resetSnake(){ snake=[{x:8,y:7},{x:7,y:7},{x:6,y:7}];direction={x:1,y:0};nextDirection=direction;food=randomFood();score=0;document.querySelector('#snake-score').textContent='0';clearInterval(loop);loop=setInterval(tick,115);draw(); }
    function setDirection(x,y){if(direction.x+x!==0||direction.y+y!==0)nextDirection={x:x,y:y};}
    function tick(){direction=nextDirection;var head={x:snake[0].x+direction.x,y:snake[0].y+direction.y};if(head.x<0)head.x=cols-1;if(head.x>=cols)head.x=0;if(head.y<0)head.y=rows-1;if(head.y>=rows)head.y=0;if(snake.some(function(s){return s.x===head.x&&s.y===head.y;})){resetSnake();return;}snake.unshift(head);if(head.x===food.x&&head.y===food.y){score++;document.querySelector('#snake-score').textContent=String(score);food=randomFood();}else snake.pop();draw();}
    function draw(){ctx.fillStyle='#02070e';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='rgba(255,255,255,.035)';for(var x=0;x<=canvas.width;x+=size){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke();}for(var y=0;y<=canvas.height;y+=size){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke();}snake.forEach(function(s,i){ctx.fillStyle=i===0?'#ffe56d':'#ffcf00';ctx.shadowColor='#ffcf00';ctx.shadowBlur=10;ctx.fillRect(s.x*size+2,s.y*size+2,size-4,size-4);ctx.shadowBlur=0;});ctx.fillStyle='#9b6cff';ctx.beginPath();ctx.arc(food.x*size+10,food.y*size+10,7,0,Math.PI*2);ctx.fill();}
    document.addEventListener('keydown',function(e){var m={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(m[e.key]){e.preventDefault();setDirection(m[e.key][0],m[e.key][1]);}});document.querySelectorAll('[data-direction]').forEach(function(b){b.addEventListener('click',function(){var m={left:[-1,0],right:[1,0],up:[0,-1],down:[0,1]},v=m[b.dataset.direction];setDirection(v[0],v[1]);});});document.querySelector('#snake-restart').addEventListener('click',resetSnake);resetSnake();
  }

  var memoryBoard=document.querySelector('#memory-board');
  if(memoryBoard){var symbols=['React','Node','Mongo','API'],opened=[],matched=0,moves=0,locked=false;function shuffle(a){return a.sort(function(){return Math.random()-.5;});}function setupMemory(){opened=[];matched=0;moves=0;locked=false;memoryBoard.innerHTML='';document.querySelector('#memory-moves').textContent='0';document.querySelector('#memory-pairs').textContent='0/4';shuffle(symbols.concat(symbols)).forEach(function(s){var b=document.createElement('button');b.className='memory-tile';b.textContent=s;b.addEventListener('click',function(){if(locked||b.classList.contains('open')||b.classList.contains('matched'))return;b.classList.add('open');opened.push(b);if(opened.length===2){moves++;document.querySelector('#memory-moves').textContent=String(moves);if(opened[0].textContent===opened[1].textContent){opened.forEach(function(x){x.classList.add('matched');});matched++;document.querySelector('#memory-pairs').textContent=matched+'/4';opened=[];}else{locked=true;setTimeout(function(){opened.forEach(function(x){x.classList.remove('open');});opened=[];locked=false;},650);}}});memoryBoard.appendChild(b);});}document.querySelector('#memory-restart').addEventListener('click',setupMemory);setupMemory();}

  var reaction=document.querySelector('#reaction-zone');
  if(reaction){var timer,startTime,state='idle',best=Number(localStorage.getItem('reactionBest'))||0,count=0;function text(a,b){reaction.querySelector('span').textContent=a;reaction.querySelector('small').textContent=b;}if(best)document.querySelector('#reaction-best').textContent=best+' ms';reaction.addEventListener('click',function(){if(state==='idle'||state==='done'){state='waiting';reaction.className='reaction-zone waiting';text('Wait for gold…','Clicking early resets the test.');timer=setTimeout(function(){state='ready';startTime=performance.now();reaction.className='reaction-zone ready';text('CLICK NOW!','');},1000+Math.random()*2600);}else if(state==='waiting'){clearTimeout(timer);state='idle';reaction.className='reaction-zone';text('Too early! Try again','Click to restart.');}else if(state==='ready'){var ms=Math.round(performance.now()-startTime);count++;if(!best||ms<best){best=ms;localStorage.setItem('reactionBest',String(best));}document.querySelector('#reaction-latest').textContent=ms+' ms';document.querySelector('#reaction-best').textContent=best+' ms';document.querySelector('#reaction-count').textContent=String(count);state='done';reaction.className='reaction-zone';text(ms+' ms','Click to test again.');}});}

  var preview=document.querySelector('#studio-preview');if(preview){function studio(){var color=document.querySelector('#studio-color').value,radius=document.querySelector('#studio-radius').value,title=document.querySelector('#studio-title').value,theme=document.querySelector('#studio-theme').value;preview.style.setProperty('--studio-accent',color);preview.style.borderColor=color;preview.style.borderRadius=radius+'px';preview.querySelector('h4').textContent=title||'Your headline';preview.querySelector('button').style.background=color;preview.querySelector('span').style.color=color;preview.className='studio-preview '+theme;}['studio-color','studio-radius','studio-title','studio-theme'].forEach(function(id){document.querySelector('#'+id).addEventListener('input',studio);});studio();}

  var run=document.querySelector('#run-code');if(run)run.addEventListener('click',function(){var output=document.querySelector('#code-output');try{var code=document.querySelector('#code-input').value;if(code.length>1000)throw new Error('Code is limited to 1000 characters.');var result=Function('"use strict";'+code)();output.textContent=JSON.stringify(result,null,2);output.style.color='#43d17e';}catch(e){output.textContent=e.name+': '+e.message;output.style.color='#ff7b87';}});

  var projects=[{name:'PHE India CRM',tech:'React · Node · CRM'},{name:'Lotus Rice Portal',tech:'Full Stack · Business Portal'},{name:'Nexus CRM',tech:'MERN · Analytics'},{name:'MediFlow HMS',tech:'React · REST API'},{name:'FleetPulse',tech:'Next.js · WebSockets'},{name:'AssistAI Support',tech:'AI API · Node.js'}],list=document.querySelector('#project-list');function renderProjects(q){if(!list)return;var data=projects.filter(function(p){return(p.name+' '+p.tech).toLowerCase().includes(q.toLowerCase());});list.innerHTML='';data.forEach(function(p){var row=document.createElement('div');row.className='project-row';row.innerHTML='<div><strong>'+p.name+'</strong><br><span>'+p.tech+'</span></div><b>READY</b>';list.appendChild(row);});document.querySelector('#project-count').textContent=data.length+' result'+(data.length===1?'':'s');}var search=document.querySelector('#project-search');if(search)search.addEventListener('input',function(){renderProjects(search.value);});renderProjects('');

  var apiSend=document.querySelector('#api-send');if(apiSend)apiSend.addEventListener('click',async function(){var resource=document.querySelector('#api-resource').value,status=document.querySelector('#api-status'),time=document.querySelector('#api-time'),output=document.querySelector('#api-output'),started=performance.now();apiSend.disabled=true;apiSend.textContent='Loading…';status.textContent='Pending';try{var response=await fetch('https://jsonplaceholder.typicode.com/'+resource);var data=await response.json();time.textContent=Math.round(performance.now()-started)+' ms';status.textContent=response.status+' '+response.statusText;output.textContent=JSON.stringify(data,null,2);}catch(e){status.textContent='Network error';output.textContent='API unavailable: '+e.message;}finally{apiSend.disabled=false;apiSend.textContent='Send Request';}});
});
